### PR TITLE
Use uname -m if uname -p returns "unknown"

### PR DESCRIPTION
**Pull request by xyproto**
Fix `server/Makefile` for Arch Linux.

### CODE REVIEW

**Comment by helloer** [comment]
Maybe you could do the same with `client/Makefile`?

**Comment by xyproto** [comment]
Sure thing

**Comment by sternenseemann** [comment]
Could drop `uname -p` altogether, it's not really portable.

**Comment by xyproto** [comment]
I don't think it makes sense for me to make general improvements to the Makefile as long as the game does not build here.

See also: #51

**Review by Shoozza — APPROVED** [review]

**Pull request merged**
