### PR TITLE
CMake fixes: use GNUInstallDirs, respect ADD_ASSETS for play-regular.ttf

### PR DESCRIPTION
**Pull request by sternenseemann**
* play-regular.ttf was installed even if `ADD_ASSETS` is `OFF` which fails
* use `GNUInstallDirs` to determine where to install libraries / executables

### CODE REVIEW

**Comment by BranDougherty** [comment]
I'm not sure if its enough for your packaging use case but you can load soldat.smod and play-regular.ttf from anywhere with the `fs_basepath` cvar (you also have to set `-fs_portable 0` on client).

**Comment by sternenseemann** [comment]
> I'm not sure if its enough for your packaging use case but you can load soldat.smod and play-regular.ttf from anywhere with the `fs_basepath` cvar (you also have to set `-fs_portable 0` on client).

I'm aware, as this is precisely what we are doing. However, without def3a93b4a72f76ca45613ae81834cab41492966 `soldat` will fail during installation with `-DADD_ASSETS=OFF` since `play-regular.ttf` is missing from the build directory (as we build / download it separately).

**Review by BranDougherty — APPROVED** [review]
I'm reasonably sure we don't actually want to do this on Windows or Mac so I added some variables to control the target install directories. Other than that this LGTM thanks!

**Comment by sternenseemann** [comment]
We (= nixpkgs) would still like to use `GNUInstallDir` on macOS *in the same way* as on Linux… I think `GNUInstallDirs` is supposed to exhibit reasonable behavior on macOS and Windows as well, isn't it?

**Comment by BranDougherty** [comment]
I'm not very knowledgeable about packaging software but I don't consider the default GNUInstallDirs Windows behavior to be good for Soldat. It puts the executables in bin and the libraries in lib FHS-style, but there's no RPATH on Windows and AFAIK we would have to generate wrapper scripts to make that install output actually usable. A flat structure just seems better.

The macOS case makes sense and we should support it. I think there is a slight conflict with the current mac build (which seems aimed at producing a standalone `.app` file although it appears incomplete) but we can work around that easily when the time comes. So just changing the condition to include GNUInstallDirs to `if(UNIX)` should be enough, right? If you can make another PR I can merge it right away.

**Comment by sternenseemann** [comment]
I may look into it in the future. At the moment we have no way to bootstrap fpc on darwin IIRC, so this is a bit theoretical…

**Pull request merged**
