### PR TITLE
Fix non-CMake builds

### PR DESCRIPTION
**Pull request by SwamiUmami**
When building client and server with methods other than CMake, I noticed that linking errors occur, either when building, or when running executables. I'm talking about stb and GameNetworkingSockets libraries. Problems occur both with Makefile and with Lazarus build.

To fix errors on build, I had to change [-Fl](https://www.freepascal.org/docs-html/user/userap1.html) parameter that controls path to libraries. According to README.md, libraries, `soldat.smod` and `play-regular.ttf` should be copied to `build` folder. But when building Soldat, we look for libraries in `libs` folder.

After building game with Lazarus, I noticed that I can't run client and server because they can't find shared libraries (stb, GameNetworkingSockets). This problem occurs at runtime, and only affects Lazarus builds on Linux. When looking at `.lpi` files, I saw that rpath setting is missing. So, in last commit I added rpath setting.

### CODE REVIEW

**Comment by BranDougherty** [comment]
Thanks for the PR, this is a step in the right direction. But there is no reason to make the directory change just for Linux, go through and change all the `<Libraries Value="libs"/>` to `<Libraries Value="build"/>` in both .lpi files and then this should be good to merge.

**Comment by SwamiUmami** [comment]
**Summary**
- Set path of libraries to `build` in all non-CMake builds
- Set rpath for Lazarus builds on Linux. Windows and MacOS builds should work fine with current code
- Removed `client/soldat.res` file from git. I don't think it's needed. See https://wiki.freepascal.org/File_extensions

**Comment by SwamiUmami** [comment]
Some other things that may be improved in Lazarus builds:
- Remove unused paths from `<SearchPaths>` in `.lpi` files (Indy10 for example)
- Maintenance is not pleasant and prone to errors. I don't think it's possible to call `make` and rely on Makefile in Lazarus builds. As an alternative, [IDE Macros](https://wiki.freepascal.org/IDE_Window:_Compiler_Options#Additions_and_Overrides) could be good to set all the paths once, and share them across multiple build targets (Windows x64, MacOS x86, etc...). As of now, making changes to a path requires changing it for each platform separately. Not sure if benefits of fixing this outweigh costs...

**Review by BranDougherty — APPROVED** [review]

**Comment by BranDougherty** [comment]
Looks like there is something wrong with vcpkg, nothing to do with this PR though. `soldat.res` is used to set the executable icon on windows, but its generated automatically by Lazarus so ignoring it is the right call. And yes both of your suggestions about improving the Lazarus projects make perfect sense.

This LGTM, thanks!

**Pull request merged**
